// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package escwebapp

import (
	"time"
)

type EscwebappContest struct {
	ContestYear         int64
	CountryIDHost       int64
	NumberOfContestants int64
}

type EscwebappMemberCountry struct {
	CountryID     int64
	CountryName   string
	BigFiveMember bool
}

type EscwebappOfficialRanking struct {
	CountryID   int64
	ContestYear int64
	PointsGiven int64
}

type EscwebappUser struct {
	UserID       int64
	UserName     string
	PassWordHash string
	Name         string
	CreatedAt    time.Time
	EMailAddress string
}

type EscwebappUserRanking struct {
	CountryID   int64
	UserID      int64
	ContestYear int64
	PointsGiven int64
}
